### ISSUE TITLE
How to use inside node?

### ISSUE THREAD

**Issue by DinisCruz** [nbubna/HTML#17]
After ```npm install html.js``` I just tried to ```var HTML = require('html.js')``` but I got the following error:

```
/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/html.js/dist/HTML.min.js:4
=e,b.addEventListener("DOMContentLoaded",function(){d.node(e,!0)})}(window,doc
                                                                    ^
ReferenceError: window is not defined
  at Object.<anonymous> (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/html.js/dist/HTML.min.js:4:3194)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_Design/node_modules/teammentor/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
```

I saw [another issue](https://github.com/nbubna/HTML/issues/10) with this error, but that was related to NW (node-webkit).

It seems that the problem is that the window (and document) objects are not available. 

Does this mean that this api cannot be used directly on node?

**Comment by nbubna** [comment]
This API requires a DOM. You need node-webkit or some other DOM provider to work. Node doesn't have a native DOM.

**Comment by DinisCruz** [comment]
ok, that is what I was thinking but wanted to make sure

Thx for the answer
